/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MediaRouteImport } from './routes/media'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DashboardMetaRouteImport } from './routes/dashboard-meta'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreativeRouteImport } from './routes/creative'
import { Route as CanvasRouteImport } from './routes/canvas'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'

const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMetaRoute = DashboardMetaRouteImport.update({
  id: '/dashboard-meta',
  path: '/dashboard-meta',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreativeRoute = CreativeRouteImport.update({
  id: '/creative',
  path: '/creative',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasRoute = CanvasRouteImport.update({
  id: '/canvas',
  path: '/canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/canvas': typeof CanvasRoute
  '/creative': typeof CreativeRoute
  '/dashboard': typeof DashboardRoute
  '/dashboard-meta': typeof DashboardMetaRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/canvas': typeof CanvasRoute
  '/creative': typeof CreativeRoute
  '/dashboard': typeof DashboardRoute
  '/dashboard-meta': typeof DashboardMetaRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/canvas': typeof CanvasRoute
  '/creative': typeof CreativeRoute
  '/dashboard': typeof DashboardRoute
  '/dashboard-meta': typeof DashboardMetaRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/canvas'
    | '/creative'
    | '/dashboard'
    | '/dashboard-meta'
    | '/explore'
    | '/login'
    | '/media'
    | '/profile'
    | '/reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/canvas'
    | '/creative'
    | '/dashboard'
    | '/dashboard-meta'
    | '/explore'
    | '/login'
    | '/media'
    | '/profile'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/canvas'
    | '/creative'
    | '/dashboard'
    | '/dashboard-meta'
    | '/explore'
    | '/login'
    | '/media'
    | '/profile'
    | '/reports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CanvasRoute: typeof CanvasRoute
  CreativeRoute: typeof CreativeRoute
  DashboardRoute: typeof DashboardRoute
  DashboardMetaRoute: typeof DashboardMetaRoute
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRoute
  MediaRoute: typeof MediaRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-meta': {
      id: '/dashboard-meta'
      path: '/dashboard-meta'
      fullPath: '/dashboard-meta'
      preLoaderRoute: typeof DashboardMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creative': {
      id: '/creative'
      path: '/creative'
      fullPath: '/creative'
      preLoaderRoute: typeof CreativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas': {
      id: '/canvas'
      path: '/canvas'
      fullPath: '/canvas'
      preLoaderRoute: typeof CanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CanvasRoute: CanvasRoute,
  CreativeRoute: CreativeRoute,
  DashboardRoute: DashboardRoute,
  DashboardMetaRoute: DashboardMetaRoute,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRoute,
  MediaRoute: MediaRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
